"""CLI: run the simulator validation study.

Examples:
    livelift-simulate --reps 50 --sessions 10 --effect 0.15
    livelift-simulate --reps 100 --sessions 10 --effect 0.0        # A/A study
    livelift-simulate --reps 50 --sessions 10 --effect 0.15 --carryover 120
    python -m livelift.sim.cli --grid                              # SBC skeleton
"""

from __future__ import annotations

import argparse
from pathlib import Path

from livelift.console import configure as _configure_console
from livelift.core.assigner.outer import DesignParams
from livelift.sim.report import render_report
from livelift.sim.simulator import SimParams
from livelift.sim.validate import default_grid, run_grid, run_validation

DEFAULT_REPORT_PATH = "docs/benchmarks/sim-validation-report.md"

# session_click_sigma values and the ICC each one produced, MEASURED on 400
# sessions x 90 min (canonical table: ICC_MAP_DOC below, regenerated by
# ICC_MAP_COMMAND). The labels quote the measured ICC so the report never
# implies a calibration that was not run.
GRID_SIGMA_ICC: dict[float, str] = {0.0: "ICC≈0.01 (σ=0)", 0.06: "ICC≈0.05 (σ=0.06)"}

# Canonical home of the measured σ → ICC map. It is NOT transcribed here: a
# table of measurements copied by hand into a second file is a drift hazard, and
# the copy is the one that silently goes stale. The report links to the file that
# a single command regenerates, and quotes only the two anchors it actually runs.
ICC_MAP_DOC = "docs/benchmarks/sim-icc-map.md"
ICC_MAP_COMMAND = "python analysis/calibration/bang_icc_mo_phong.py"


def _sigma_icc_markdown() -> str:
    return (
        "### Ánh xạ σ → ICC (đo được, không giả định)\n"
        "\n"
        f"Bảng đầy đủ (σ ∈ {{0; 0,03; 0,06; 0,095; 0,1; 0,2; 0,3}}) nằm ở `{ICC_MAP_DOC}` và "
        f"sinh lại được bằng một lệnh:\n\n```\n{ICC_MAP_COMMAND}\n```\n"
        "\n"
        "400 phiên × 90 phút, khối 5 phút, burn-in 60 giây, tác động 0; ICC = ANOVA một "
        "chiều của `y` theo cụm phiên (`livelift.sim.report.session_icc`); ± là sai số "
        "chuẩn bootstrap theo CỤM PHIÊN. Không chép lại bảng vào đây: một bảng SỐ ĐO chép "
        "tay sang file thứ hai là chỗ để hai con số lặng lẽ lệch nhau.\n"
        "\n"
        "Hai mốc mà lưới trên thực sự chạy: **σ=0 → ICC +0,008 ± 0,005** và "
        "**σ=0,06 → ICC +0,048 ± 0,008**.\n"
        "\n"
        "σ=0 cho ICC≈0,01 **chứ không phải 0**: ICC(1) theo ANOVA lệch lên khi phương sai "
        "trong-cụm không đều, mà `session_shock_sd` (cú sốc lượt vào) làm đúng thế. Đó là "
        "số đo, không phải giả định.\n"
    )


def _grid_header(args: argparse.Namespace, sessions: int, minutes: int, draws: int) -> str:
    cmd = (
        f"python -m livelift.sim.cli --grid --grid-reps {args.grid_reps} "
        f"--sessions {sessions} --minutes {minutes} "
        f"--effect {args.effect} --draws {draws} --seed {args.seed}"
    )
    return (
        "# Thẩm định mô phỏng — lưới SBC (BỘ KHUNG / SKELETON)\n"
        "\n"
        f"Lệnh tái lập (sinh chính file này):\n\n```\n{cmd}\n```\n"
        "\n"
        "**TRẠNG THÁI: SKELETON.** Lưới ở đây chỉ có "
        f"{len(GRID_SIGMA_ICC)}×2 = {2 * len(GRID_SIGMA_ICC)} ô × {args.grid_reps} lần lặp — "
        "đủ để chứng minh đường ống chạy và ô ĐỎ là *có thể chạm tới* "
        "(test nghịch đảo trong `tests/test_sim_report.py`), CHƯA phải bằng chứng "
        "hiệu chuẩn đầy đủ. Lưới đầy đủ (~20 ô: hiệu ứng lưu × ICC × tác động, "
        "1000 lần lặp/ô) là việc của tuần khóa tiền đăng ký; con số của nó KHÔNG "
        "được suy đoán từ đây.\n"
        "\n"
        "Ba tiêu chí mỗi ô (HARNESS.md §2):\n"
        "\n"
        "1. **Đồng đều p-value** — chỉ kiểm ở ô A/A, nơi giả thuyết không sắc thực sự "
        "đúng. `D` là độ lệch ECDF lớn nhất (cũng chính là thống kê KS); nó được đối "
        "chiếu hai lần: với p-value chính xác của KS, và với băng đồng thời 95% kiểu "
        "DKW/Massart — băng này *bảo thủ* ở n nhỏ nên KS mới là công cụ sắc.\n"
        "2. **Độ phủ** khoảng tin cậy Fisher: khoảng Wilson quanh tỷ lệ phủ quan sát "
        "phải chứa mức danh nghĩa 95%. Khoảng lấy ở mức 99% (không phải 95%) theo đúng "
        "quy ước của các cổng hiệu chuẩn sẵn có — phán quyết ở mức 5% sẽ làm một ô "
        "ĐỎ oan cứ mỗi 20 ô dù đường ống hoàn hảo.\n"
        "3. **Lệch** so với chân trị CRN: < 10% tác động thật. Ở ô A/A tác động thật "
        "≈ 0 nên không có mẫu số — báo lệch TUYỆT ĐỐI kèm sai số Monte-Carlo thay vì "
        "bịa một tỷ lệ phần trăm chia cho ~0.\n"
        "\n"
        f"Ghi chú về cột tác động: `{args.effect:g}` là mức đang dùng cho cổng hiệu "
        "chuẩn hiện có, **không** phải MDE đã đo. Bảng MDE trong PREREGISTRATION.md §6 "
        "còn là ô trống chờ số hiệu chỉnh tuần 3–4; khi có, ô này chạy lại ở đúng MDE.\n"
        "\n"
        "Trục ICC là knob `SimParams.session_click_sigma` (gói P1-K2); mục cuối file nói "
        f"σ nào cho ICC nào, bảng đầy đủ (SỐ ĐO, sinh lại được) ở `{ICC_MAP_DOC}`. "
        "Hai cổng Monte-Carlo `-m slow` chạy đúng thế giới ICC≈0,05 này với "
        "NGUYÊN ngưỡng của bản không phân cụm: "
        "`test_aa_false_positive_rate_near_alpha_under_session_icc` và "
        "`test_effect_recovery_bias_and_coverage_under_session_icc`.\n"
    )


def _run_grid(args: argparse.Namespace, sessions: int, minutes: int, draws: int) -> int:
    specs = default_grid(
        sigmas=tuple(GRID_SIGMA_ICC),
        effects=(0.0, args.effect),
        icc_labels=GRID_SIGMA_ICC,
        n_reps=args.grid_reps,
        n_sessions_per_rep=sessions,
        session_minutes=minutes,
        n_draws=draws,
        burn_in_s=args.burn_in,
        master_seed=args.seed,
        design=DesignParams(block_min=args.block),
    )
    cells = run_grid(specs)
    text = render_report(cells, header=_grid_header(args, sessions, minutes, draws))
    text += "\n" + _sigma_icc_markdown()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(text)
    print(f"→ đã ghi {out}")
    return 0


def main(argv: list[str] | None = None) -> int:
    _configure_console()
    parser = argparse.ArgumentParser(prog="livelift-simulate", description=__doc__)
    parser.add_argument("--reps", type=int, default=50)
    # These three carry MODE-DEPENDENT defaults (resolved below): the single
    # study is meant to be precise, the grid is meant to finish over a coffee.
    # A bare `--grid` inheriting 10 sessions x 90 min x 500 draws x 100 reps x
    # 4 cells would run for hours and nobody would ever regenerate the report.
    parser.add_argument(
        "--sessions", type=int, default=None, help="sessions per replication (default 10; grid 3)"
    )
    parser.add_argument("--minutes", type=int, default=None, help="default 90; grid 60")
    parser.add_argument("--block", type=int, default=5)
    parser.add_argument("--effect", type=float, default=0.15)
    parser.add_argument("--carryover", type=float, default=0.0, help="carryover half-life, seconds")
    parser.add_argument("--burn-in", type=int, default=60, help="analysis burn-in, seconds")
    parser.add_argument(
        "--draws", type=int, default=None, help="randomization draws (default 500; grid 200)"
    )
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument(
        "--frailty-cv",
        type=float,
        default=0.0,
        help="per-viewer click frailty CV (Gamma, mean 1); 0 = homogeneous audience",
    )
    parser.add_argument(
        "--click-sigma",
        type=float,
        default=0.0,
        help="session-level click multiplier sigma — the outcome-ICC knob; 0 = no clustering",
    )
    parser.add_argument(
        "--grid",
        action="store_true",
        help=(
            "run the SBC skeleton grid and write the markdown report; the grid "
            "defines its own worlds, so --reps/--carryover/--frailty-cv/--click-sigma "
            "are ignored (use --grid-reps and --effect)"
        ),
    )
    parser.add_argument("--grid-reps", type=int, default=100, help="replications per grid cell")
    parser.add_argument("--out", default=DEFAULT_REPORT_PATH, help="grid report output path")
    args = parser.parse_args(argv)

    sessions = args.sessions if args.sessions is not None else (3 if args.grid else 10)
    minutes = args.minutes if args.minutes is not None else (60 if args.grid else 90)
    draws = args.draws if args.draws is not None else (200 if args.grid else 500)

    if args.grid:
        return _run_grid(args, sessions, minutes, draws)

    design = DesignParams(block_min=args.block)
    sim = SimParams(
        treatment_effect=args.effect,
        carryover_halflife_s=args.carryover,
        click_frailty_cv=args.frailty_cv,
        session_click_sigma=args.click_sigma,
    )
    result = run_validation(
        n_reps=args.reps,
        n_sessions_per_rep=sessions,
        session_minutes=minutes,
        design=design,
        sim_params=sim,
        burn_in_s=args.burn_in,
        n_draws=draws,
        master_seed=args.seed,
    )
    print(result.summary())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
