"""Shopee Live ingestion via the OFFICIAL Shopee Open Platform API v2.

Đây là đường **chính thức, hợp Điều khoản dịch vụ** — khác hẳn TikTok
(dịch ngược, đã bị chặn) và yt-dlp (trái ToS của YouTube). Nó đọc buổi live của
**chính shop mình** bằng token do chủ shop tự cấp qua OAuth của Shopee.

Kiểm chứng thật ngày 11/09/2026 (xem ``docs/nen-tang-ho-tro.md`` §4):

- ``GET https://partner.shopeemobile.com/api/v2/livestream/get_latest_comment_list``
  TỒN TẠI: gọi không tham số trả ``{"error":"error_param","message":"There is no
  partner_id in query."}``, trong khi một đường dẫn bịa
  (``/api/v2/livestream/khong_ton_tai_abc``) trả **HTTP 404
  ``error_not_found``**. Đối chứng này là bằng chứng endpoint có thật, không
  phải suy đoán.
- Ký thử (partner_id/partner_key giả) → ``HTTP 403 invalid_partner_id`` — cổng
  API từ chối ở bước partner_id, TRƯỚC khi kiểm chữ ký, nên phép thử này
  **không** chứng minh được lược đồ ký. Nhóm chưa có ``SHOPEE_PARTNER_ID`` nên
  **chưa đọc được bình luận thật**; mọi hành vi dưới đây có test ngoại tuyến,
  chưa có live-fire.
- Tài liệu endpoint ghi rõ ``(For TW, ID, TH, PH, MY, SG, VN)`` — **có Việt Nam**.

Xác thực loại "User" (sửa 17/09/2026)
-------------------------------------
Nguồn: JSON tài liệu gốc tải từ open.shopee.com ngày 17/09/2026 cho bảy endpoint
``v2.livestream.*`` (create_session, get_latest_comment_list,
get_session_detail, get_session_metric, get_session_item_metric, post_comment,
update_show_item). Cả bảy có ``"api_type": "User"`` và ``common_params`` đúng
năm trường ``partner_id, timestamp, access_token, user_id, sign``; mô tả
``sign`` nguyên văn: *"Signature generated by(depends on different APIs)
partner_id, api path, timestamp, access_token, user_id and partner_key via
HMAC-SHA256 hashing algorithm."* Mẫu yêu cầu của tài liệu cũng chỉ có
``...&sign=sign&timestamp=timestamp&user_id=user_id`` — **không có**
``shop_id`` trong query.

Trước 17/09 adapter ký bằng ``shop_id`` (lược đồ của API loại "Shop") và gửi
``shop_id`` thay cho ``user_id``, lại còn ký trên phần ĐUÔI
``/livestream/...`` thay vì đường dẫn đầy đủ ``/api/v2/livestream/...``. Hai lỗi
đó đủ để mọi lời gọi thật bị từ chối. ``user_id`` ở đây là tài khoản NGƯỜI PHÁT
đã ủy quyền cho app (``user_id_list`` trong phản hồi
``v2.public.get_access_token``) — **không** liên quan tới ``user_id`` của người
bình luận trong phản hồi ``get_latest_comment_list``.

``shop_id`` chỉ còn một chỗ dùng: tham số THÂN (body) bắt buộc của
``update_show_item`` (ghim sản phẩm).

Ba đặc tính của API này định hình toàn bộ thiết kế dưới đây:

1. **Cửa sổ 10 giây.** ``get_latest_comment_list`` chỉ trả bình luận *trong 10
   giây gần nhất*. Poll chậm hơn 10 s là **mất dữ liệu vĩnh viễn** — không có
   con trỏ ``since`` để quay lại như Facebook. Vì vậy :data:`MAX_SAFE_POLL_S`
   được ép cứng: truyền ``poll_s`` lớn hơn sẽ **báo lỗi ngay**, chứ không âm
   thầm bỏ sót bình luận trong một thí nghiệm nhân quả.
2. **Chữ ký nằm trong query string.** Lược đồ ký của Shopee bắt buộc
   ``access_token`` và ``user_id`` phải là *tham số query* (chúng nằm trong
   chuỗi cơ sở của HMAC). Không thể đẩy token sang header như Facebook. Nên
   mọi lỗi ở đây được gói lại thành :class:`ShopeeApiError` — thông điệp
   **không bao giờ chứa URL**, vì ``httpx`` nhét URL đầy đủ vào mọi
   ``HTTPStatusError`` và token sẽ lọt vào traceback/log.
   Riêng log của ``httpx``: ở mức INFO nó tự in dòng ``HTTP Request: GET <URL>``
   với URL đầy đủ; runner CLI bật INFO nên token từng lọt thẳng ra màn hình
   (đo 17/09/2026). Bộ lọc log chung ở :mod:`livelift.ingest.base` che
   ``access_token``/``refresh_token``/``sign`` (và ``key=`` của YouTube) trong
   các dòng đó trước khi ra bất kỳ handler nào.
3. **Có tín hiệu chuyển đổi thật.** ``get_session_metric`` trả ``gmv``,
   ``orders``, ``atc``, ``ctr``, ``ccu``, ``peak_ccu`` — thứ mà YouTube và
   TikTok **không** có. Đây là lý do Shopee đáng đầu tư: nó là nền tảng duy
   nhất khảo sát được hôm nay vừa cho bình luận vừa cho kết quả thương mại
   qua một API chính thức.

Quyền riêng tư (hard rule 1): phản hồi bình luận **có** ``user_id`` và
``username``. :func:`parse_comment` chỉ đọc ``comment_id``/``content``/
``timestamp`` — hai trường định danh **không bao giờ** ra khỏi hàm này, kể cả
vào log. Văn bản thô được :class:`livelift.ingest.base.ApiSink` lọc PII trước
khi truyền đi.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import logging
import time
from collections import deque
from collections.abc import AsyncIterator, Iterable, Mapping
from datetime import UTC, datetime
from typing import Any, Literal
from urllib.parse import urlsplit

import httpx

from livelift.config import get_settings

# Nhập base cũng là cài bộ lọc che bí mật trong log httpx (access_token/sign
# của Shopee, key= của YouTube) — kiểm toán 17/09/2026 chuyển nó từ tệp này
# sang base.py để phủ MỌI nền tảng.
from livelift.ingest.base import Backoff, RawComment, RawTick

logger = logging.getLogger(__name__)

#: Cổng API theo vùng (src/schemas/region.ts của SDK Shopee, tra 11/09/2026).
#: Việt Nam dùng cổng GLOBAL — Shopee **không** có host riêng cho .vn.
REGION_BASE_URLS: dict[str, str] = {
    "global": "https://partner.shopeemobile.com/api/v2",
    "china": "https://openplatform.shopee.cn/api/v2",
    "brazil": "https://openplatform.shopee.com.br/api/v2",
    "sandbox": "https://openplatform.sandbox.test-stable.shopee.sg/api/v2",
}
DEFAULT_REGION = "global"

#: Đường dẫn tính từ ``REGION_BASE_URLS`` (tức là SAU ``/api/v2``). Chữ ký
#: luôn tính trên đường dẫn ĐẦY ĐỦ — xem :meth:`ShopeeLiveClient._api_path`.
PATH_COMMENTS = "/livestream/get_latest_comment_list"
PATH_METRIC = "/livestream/get_session_metric"
PATH_DETAIL = "/livestream/get_session_detail"
PATH_SHOW_ITEM = "/livestream/update_show_item"

#: Biến môi trường BẮT BUỘC cho mọi lời gọi livestream (đọc bình luận, người
#: xem, chỉ số). Nguồn: ``common_params`` của tài liệu ``v2.livestream.*``.
REQUIRED_ENV_LIVESTREAM: tuple[str, ...] = (
    "SHOPEE_PARTNER_ID",
    "SHOPEE_PARTNER_KEY",
    "SHOPEE_USER_ID",
    "SHOPEE_ACCESS_TOKEN",
)
#: Ghim sản phẩm (``update_show_item``) cần thêm ``shop_id`` trong thân yêu cầu.
REQUIRED_ENV_SHOW_ITEM: tuple[str, ...] = (*REQUIRED_ENV_LIVESTREAM, "SHOPEE_SHOP_ID")
#: Tài liệu khai ``int``/``int64`` cho các định danh này.
_NUMERIC_ENV = frozenset({"SHOPEE_PARTNER_ID", "SHOPEE_USER_ID", "SHOPEE_SHOP_ID"})

#: Cửa sổ dữ liệu của ``get_latest_comment_list`` theo tài liệu Shopee.
COMMENT_WINDOW_S = 10.0
#: Nhịp poll tối đa còn an toàn. Vượt ngưỡng này là chắc chắn mất bình luận
#: (cửa sổ 10 s trôi qua giữa hai lần gọi), nên client **từ chối chạy**.
MAX_SAFE_POLL_S = 8.0
DEFAULT_POLL_S = 5.0
DEFAULT_TICK_S = 30.0

#: Số trang ``next_offset`` theo trong MỘT lần poll. Cửa sổ chỉ 10 s nên một
#: phòng rất đông vẫn hiếm khi vượt vài trang; chặn trên để không kẹt vòng lặp.
MAX_PAGES_PER_POLL = 20
_SEEN_IDS_MAX = 2048

AUTH_BACKOFF_S = 60.0
RATE_LIMIT_BACKOFF_S = 300.0
RETRY_CAP_S = 60.0

#: ``status`` của ``get_session_detail``: 0 = chưa bắt đầu, 1 = đang phát,
#: 2 = đã kết thúc.
STATUS_INIT = 0
STATUS_ONGOING = 1
STATUS_ENDED = 2

#: Mảnh chuỗi trong trường ``error`` của Shopee nghĩa là "người vận hành phải
#: sửa danh tính" — thử lại nhanh không cứu được.
#: CHƯA KIỂM CHỨNG TRÊN TÀI KHOẢN THẬT: nhóm chưa có partner_id, nên danh sách
#: này dựng từ quy ước đặt tên mã lỗi của Shopee chứ không phải từ lỗi đã gặp.
#: Nhánh mặc định là "transient" (thử lại) nên phân loại sai chỉ làm chậm chứ
#: không làm hỏng dữ liệu.
AUTH_ERROR_MARKERS = (
    "auth",
    "token",
    "sign",
    "permission",
    "partner_id",
    "user_id",
    "shop_id",
    "forbid",
)
#: Mảnh chuỗi nghĩa là "đang bị bóp nhịp gọi" — token vẫn tốt, chỉ cần nghỉ.
RATE_LIMIT_MARKERS = ("rate", "limit", "too many", "frequen", "busy")

#: Ba thông điệp dưới đây chép NGUYÊN VĂN từ ``error_list`` của tài liệu
#: ``v2.livestream.*`` (so khớp không phân biệt hoa thường):
#:   "The API is not supported for current region"      (error_server)
#:   "The session(session_id:{{sid}}) is not ongoing"   (error_data)
#:   "Invalid session_id" · "The session(session_id:{{sid}}) is not exist"
#:   · "The session(session_id:{{sid}}) is not belong to you"
REGION_ERROR_MARKER = "not supported for current region"
NOT_LIVE_ERROR_MARKER = "is not ongoing"

ErrorKind = Literal["auth", "rate_limit", "region", "not_live", "session", "transient"]


class ShopeeApiError(Exception):
    """Lỗi từ Shopee Open Platform, **đã bỏ URL**.

    Lý do tồn tại: lược đồ ký của Shopee bắt buộc ``access_token`` nằm trong
    query string. ``httpx.HTTPStatusError`` in nguyên URL vào thông điệp, nên
    nếu để nó nổi lên thì token của shop sẽ nằm trong traceback và trong mọi
    dòng log ``logger.exception``. Lớp này chỉ mang mã trạng thái, mã lỗi và
    ``request_id`` — đủ để gỡ rối, không đủ để lộ khóa.
    """

    #: Câu tiếng Việt đặt TRƯỚC chi tiết kỹ thuật (lớp con ghi đè). Đứng đầu
    #: để vẫn còn nguyên khi bộ giám sát cắt thông điệp ở 400 ký tự.
    giai_thich: str = ""

    def __init__(
        self,
        code: str,
        message: str = "",
        status: int | None = None,
        request_id: str | None = None,
    ) -> None:
        self.code = code
        self.api_message = message
        self.status = status
        self.request_id = request_id
        detail = f"Shopee API lỗi {code!r}"
        if status is not None:
            detail += f" (HTTP {status})"
        if message:
            detail += f": {message}"
        if request_id:
            detail += f" [request_id={request_id}]"
        if self.giai_thich:
            detail = f"{self.giai_thich} [{detail}]"
        super().__init__(detail)


class ShopeeRegionError(ShopeeApiError, ValueError):
    """Tài khoản ở vùng này chưa được cấp API livestream — lỗi CẤU HÌNH.

    Kế thừa ``ValueError`` có chủ ý: bộ giám sát trong
    ``livelift.api.ingest_jobs`` coi ``ValueError`` là lỗi cấu hình (dừng ngay,
    không đốt 20 lần thử lại) và hiện nguyên thông điệp cho người vận hành.
    """

    giai_thich = (
        "Tài khoản Shopee này CHƯA được cấp API livestream ở vùng hiện tại. Thử lại "
        "không sửa được: kiểm tra app trên open.shopee.com đã được duyệt nhóm "
        "Livestream cho Việt Nam chưa, và SHOPEE_REGION=global."
    )


class ShopeeSessionError(ShopeeApiError, ValueError):
    """``session_id`` sai hoặc không thuộc tài khoản đã ủy quyền — lỗi CẤU HÌNH."""

    giai_thich = (
        "session_id không đúng hoặc không thuộc tài khoản đã ủy quyền "
        "(SHOPEE_USER_ID). Kiểm tra lại mã buổi live đã dán."
    )


class ShopeeNotLiveError(ShopeeApiError, RuntimeError):
    """Phiên tồn tại nhưng không đang phát.

    Thông điệp chứa NGUYÊN VĂN cụm "KHÔNG có buổi live nào đang phát" — bộ giám
    sát nhận diện đúng cụm đó để chuyển sang trạng thái chờ lên sóng thay vì
    tính là lỗi.

    Hợp đồng với nơi gọi: client **KHÔNG tự chờ** — lỗi này nổi lên ngay để nơi
    gọi quyết định chờ. Bộ giám sát web (``ingest_jobs``) bắt nó (qua cụm chữ trên)
    rồi dò lại sau một nhịp chờ.

    LỖI CÒN MỞ ở runner CLI (``livelift.ingest.runner.main``, đo 17/09/2026):
    ``main`` chỉ bắt ``KeyboardInterrupt`` và ``httpx.HTTPError``, nên bật
    ``--platform shopee`` TRƯỚC giờ phát thì tiến trình chết với traceback. Bản
    9e343ca không chết vì client khi đó coi "is not ongoing" là lỗi tạm thời và
    thử lại mãi. Facebook KHÔNG bị như vậy: CLI bắt buộc ``--source-id`` nên
    không gọi ``get_active_live_video_id`` (chỗ duy nhất Facebook ném "chưa
    phát"), còn ``FacebookLiveClient.iter_comments`` tự thử lại. Sửa thuộc về
    ``runner.py``; test ``test_runner_cli_started_before_go_live_does_not_crash``
    đánh dấu ``xfail(strict=True)`` khoá kịch bản này và sẽ ĐỎ khi runner đã sửa
    — lúc đó bỏ dấu xfail.
    """

    #: Không hứa "tự chờ" vô điều kiện: đúng cho Bộ thu bình luận trên web, SAI
    #: cho runner CLI hiện tại (xem docstring) — nên nói rõ cả hai đường.
    giai_thich = (
        "Shopee báo KHÔNG có buổi live nào đang phát ở session_id này (chưa bấm "
        "phát, hoặc buổi live đã tắt). Bấm phát trên app Shopee: Bộ thu bình luận "
        "trên web tự dò lại; thu bằng dòng lệnh thì chạy lại lệnh sau khi đã phát."
    )


def _error_class_for(message: str) -> type[ShopeeApiError]:
    """Chọn lớp lỗi theo thông điệp nguyên văn của Shopee."""
    text = message.lower()
    if REGION_ERROR_MARKER in text:
        return ShopeeRegionError
    if "session" in text and NOT_LIVE_ERROR_MARKER in text:
        return ShopeeNotLiveError
    if "invalid session_id" in text or (
        "session" in text and ("is not exist" in text or "not belong to you" in text)
    ):
        return ShopeeSessionError
    return ShopeeApiError


def api_error(
    code: str, message: str = "", status: int | None = None, request_id: str | None = None
) -> ShopeeApiError:
    """Dựng lỗi đúng lớp (vùng / chưa phát / sai phiên / chung) từ envelope."""
    cls = _error_class_for(message)
    return cls(code=code, message=message, status=status, request_id=request_id)


def sign_request(
    partner_id: str,
    partner_key: str,
    api_path: str,
    timestamp: int,
    access_token: str,
    user_id: str,
) -> str:
    """HMAC-SHA256 hex của ``partner_id + api_path + timestamp + access_token + user_id``.

    Lược đồ của API loại "User" (mọi ``v2.livestream.*``), theo mô tả ``sign``
    trong ``common_params`` của tài liệu gốc open.shopee.com (tải 17/09/2026).
    ``api_path`` là đường dẫn ĐẦY ĐỦ tính từ gốc host
    (``/api/v2/livestream/...``), không phải phần đuôi — ký sai phần này là lỗi
    hay gặp nhất khi tích hợp Shopee, và chính adapter này đã mắc tới 17/09.
    """
    base_string = f"{partner_id}{api_path}{timestamp}{access_token}{user_id}"
    return hmac.new(
        partner_key.encode("utf-8"), base_string.encode("utf-8"), hashlib.sha256
    ).hexdigest()


def build_signed_params(
    partner_id: str,
    partner_key: str,
    api_path: str,
    access_token: str,
    user_id: str,
    extra: dict[str, Any] | None = None,
    timestamp: int | None = None,
) -> dict[str, str]:
    """Bộ tham số query đã ký cho một lời gọi loại "User".

    Đúng năm trường chung của tài liệu: ``partner_id``, ``timestamp``,
    ``access_token``, ``user_id``, ``sign``. **Không** có ``shop_id``.
    """
    if not api_path.startswith("/api/"):
        raise ValueError(
            f"api_path={api_path!r} phải là đường dẫn ĐẦY ĐỦ (/api/v2/...): Shopee "
            "ký trên đường dẫn đầy đủ, ký phần đuôi thì mọi lời gọi bị từ chối."
        )
    ts = int(time.time()) if timestamp is None else timestamp
    params: dict[str, str] = {str(k): str(v) for k, v in (extra or {}).items()}
    params.update(
        {
            "partner_id": partner_id,
            "timestamp": str(ts),
            "access_token": access_token,
            "user_id": user_id,
            "sign": sign_request(partner_id, partner_key, api_path, ts, access_token, user_id),
        }
    )
    return params


def credential_problem(values: Mapping[str, str], required: Iterable[str]) -> str | None:
    """Câu tiếng Việt nếu thiếu/sai danh tính, None nếu đủ.

    Thông điệp bắt đầu bằng "Thiếu danh tính Shopee" — bộ giám sát trong
    ``livelift.api.ingest_jobs`` nhận diện lỗi cấu hình bằng đúng chuỗi đó.
    **Không bao giờ** chứa giá trị của khóa, chỉ tên biến.
    """
    names = list(required)
    missing = [n for n in names if not (values.get(n) or "").strip()]
    if missing:
        message = "Thiếu danh tính Shopee trong .env: " + ", ".join(missing) + "."
        bad = missing
    else:
        bad = [n for n in names if n in _NUMERIC_ENV and not values[n].strip().isdigit()]
        if not bad:
            return None
        message = "Thiếu danh tính Shopee hợp lệ trong .env: " + ", ".join(bad) + " phải là dãy số."
    if "SHOPEE_USER_ID" in bad:
        message += (
            " SHOPEE_USER_ID là mã tài khoản người phát, lấy từ user_id_list khi ủy "
            "quyền app (không phải mã shop)."
        )
    return message + " Xem docs/nen-tang-ho-tro.md §4."


def classify_error(exc: Exception) -> ErrorKind:
    """Quyết định nghỉ bao lâu, thử lại hay dừng.

    ``region``/``session`` là lỗi cấu hình (dừng), ``not_live`` là "chờ lên
    sóng", ``auth``/``rate_limit``/``transient`` là các nhịp thử lại.
    """
    if not isinstance(exc, ShopeeApiError):
        return "transient"
    cls = type(exc) if type(exc) is not ShopeeApiError else _error_class_for(exc.api_message)
    if issubclass(cls, ShopeeRegionError):
        return "region"
    if issubclass(cls, ShopeeNotLiveError):
        return "not_live"
    if issubclass(cls, ShopeeSessionError):
        return "session"
    haystack = f"{exc.code} {exc.api_message}".lower()
    if exc.status in (401, 403) or any(m in haystack for m in AUTH_ERROR_MARKERS):
        # Rate limit đôi khi cũng trả 403; ưu tiên nhận diện rate limit
        # để không bảo người vận hành đi xoay token đang còn tốt.
        if any(m in haystack for m in RATE_LIMIT_MARKERS):
            return "rate_limit"
        return "auth"
    if exc.status == 429 or any(m in haystack for m in RATE_LIMIT_MARKERS):
        return "rate_limit"
    return "transient"


def auth_error_message(exc: ShopeeApiError) -> str:
    return (
        f"XÁC THỰC Shopee THẤT BẠI ({exc.code}). Việc cần làm: chạy "
        "`python scripts/kiem_tra_shopee.py` để xem token còn hạn không — "
        "access_token của Shopee chỉ sống 4 giờ, phải là token cấp cho đúng "
        "SHOPEE_USER_ID và làm mới bằng refresh_token theo user_id. Kiểm tra cả "
        "SHOPEE_PARTNER_ID / SHOPEE_PARTNER_KEY / SHOPEE_USER_ID. Xem "
        "docs/nen-tang-ho-tro.md §4."
    )


def rate_limit_message(exc: ShopeeApiError) -> str:
    return (
        f"GIỚI HẠN nhịp gọi Shopee ({exc.code}) — token VẪN TỐT, KHÔNG cần đổi "
        f"token. Tự nghỉ {RATE_LIMIT_BACKOFF_S:.0f}s rồi chạy tiếp. Nếu lặp lại, "
        "giảm nhịp poll (nhưng KHÔNG được quá "
        f"{MAX_SAFE_POLL_S:.0f}s — cửa sổ bình luận chỉ {COMMENT_WINDOW_S:.0f}s) "
        "hoặc tắt bớt tiến trình ingest trên cùng một shop."
    )


def parse_comment(item: dict[str, Any]) -> RawComment | None:
    """Một phần tử ``response.list`` → :class:`RawComment`, hoặc None nếu hỏng.

    **Bỏ ``user_id`` và ``username``** ngay tại đây (hard rule 1 + §11.2): hai
    trường đó có trong phản hồi của Shopee nhưng không bao giờ được ra khỏi
    hàm này. ``author_ext_id`` để None chứ không phải ``user_id``, nên kể cả
    một lỗi nối dây sau này cũng không làm lộ danh tính người bình luận.
    """
    comment_id = item.get("comment_id")
    content = item.get("content")
    ts = item.get("timestamp")
    if comment_id is None or content is None or ts is None:
        return None
    try:
        ts_utc = datetime.fromtimestamp(float(ts), tz=UTC)
    except (TypeError, ValueError, OSError, OverflowError):
        return None
    return RawComment(
        platform="shopee",
        ext_id=str(comment_id),
        ts_utc=ts_utc,
        text=str(content),
        author_ext_id=None,
    )


def next_offset(data: dict[str, Any]) -> int | None:
    """``next_offset`` khi còn trang sau, None khi hết.

    Shopee trả ``next_offset`` cả khi đã hết dữ liệu, nên trang rỗng mới là
    dấu chấm hết thật; hàm này chỉ chuẩn hóa kiểu, vòng lặp quyết định dừng.
    """
    value = data.get("next_offset")
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _as_int(name: str, value: str | int) -> int:
    """Định danh kiểu ``int64`` cho thân JSON; báo lỗi tiếng Việt nếu không phải số."""
    text = str(value).strip()
    if not text.isdigit():
        raise ValueError(f"{name} của Shopee phải là một dãy số, nhận {text[:32]!r}.")
    return int(text)


class ShopeeLiveClient:
    """Client bất đồng bộ đọc bình luận + người xem của một phiên Shopee Live.

    Danh tính lấy từ :func:`get_settings` nếu không truyền tường minh. Truyền
    ``client`` (``httpx.AsyncClient`` với ``MockTransport``) để test không cần
    mạng.
    """

    def __init__(
        self,
        partner_id: str | None = None,
        partner_key: str | None = None,
        user_id: str | None = None,
        access_token: str | None = None,
        region: str | None = None,
        client: httpx.AsyncClient | None = None,
        shop_id: str | None = None,
    ) -> None:
        settings = get_settings()
        self._partner_id = partner_id if partner_id is not None else settings.shopee_partner_id
        self._partner_key = partner_key if partner_key is not None else settings.shopee_partner_key
        self._user_id = user_id if user_id is not None else settings.shopee_user_id
        self._shop_id = shop_id if shop_id is not None else settings.shopee_shop_id
        self._access_token = (
            access_token if access_token is not None else settings.shopee_access_token
        )
        region_name = (region if region is not None else settings.shopee_region).strip().lower()
        if region_name not in REGION_BASE_URLS:
            raise ValueError(
                f"SHOPEE_REGION không hợp lệ: {region_name!r} — chỉ nhận "
                f"{', '.join(sorted(REGION_BASE_URLS))}"
            )
        self._region = region_name
        self._base = REGION_BASE_URLS[region_name]
        self._client = client or httpx.AsyncClient(timeout=30.0)
        self._owns_client = client is None
        #: Lỗi gần nhất (None = khỏe) — runner in ra trong mỗi heartbeat.
        self.last_error: str | None = None
        #: Shopee KHÔNG trả header hạn mức như Facebook, nên luôn None. Giữ
        #: thuộc tính để runner dùng chung một giao diện heartbeat.
        self.last_usage_pct: float | None = None

    def _credential_values(self) -> dict[str, str]:
        return {
            "SHOPEE_PARTNER_ID": self._partner_id,
            "SHOPEE_PARTNER_KEY": self._partner_key,
            "SHOPEE_USER_ID": self._user_id,
            "SHOPEE_ACCESS_TOKEN": self._access_token,
            "SHOPEE_SHOP_ID": self._shop_id,
        }

    def require_credentials(self, *, need_shop_id: bool = False) -> None:
        """Báo lỗi tiếng Việt NGAY nếu thiếu danh tính, thay vì để Shopee trả
        ``invalid_partner_id``/``error_sign`` sau một vòng mạng.

        ``SHOPEE_SHOP_ID`` chỉ bắt buộc khi ``need_shop_id`` (ghim sản phẩm).
        """
        required = REQUIRED_ENV_SHOW_ITEM if need_shop_id else REQUIRED_ENV_LIVESTREAM
        problem = credential_problem(self._credential_values(), required)
        if problem:
            raise RuntimeError(problem)

    # -- transport ---------------------------------------------------------

    def _api_path(self, path: str) -> str:
        """``/livestream/x`` → ``/api/v2/livestream/x`` — đường dẫn được KÝ."""
        return urlsplit(self._base).path.rstrip("/") + path

    async def _call(
        self,
        method: Literal["GET", "POST"],
        path: str,
        query: dict[str, Any] | None = None,
        body: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Gọi một endpoint đã ký, trả về ``response`` của envelope.

        Tham số chung (kèm chữ ký) luôn nằm trong query; ``body`` chỉ dùng cho
        endpoint POST (thân JSON, đúng mẫu yêu cầu của tài liệu). Mọi lỗi được
        gói thành :class:`ShopeeApiError` (hoặc lớp con) — **không có URL**
        trong thông điệp, vì access_token bắt buộc phải nằm trong query string.
        """
        params = build_signed_params(
            partner_id=self._partner_id.strip(),
            partner_key=self._partner_key,
            api_path=self._api_path(path),
            access_token=self._access_token.strip(),
            user_id=self._user_id.strip(),
            extra=query,
        )
        url = self._base + path
        try:
            if method == "POST":
                resp = await self._client.post(url, params=params, json=body or {})
            else:
                resp = await self._client.get(url, params=params)
        except httpx.HTTPError as exc:
            # str(exc) của httpx có thể chứa URL (kèm token) — chỉ giữ tên lớp.
            raise ShopeeApiError(code="network", message=type(exc).__name__) from None
        try:
            payload = resp.json()
        except ValueError:
            raise ShopeeApiError(
                code="bad_json",
                message=f"phản hồi không phải JSON ({len(resp.content)} byte)",
                status=resp.status_code,
            ) from None
        if not isinstance(payload, dict):
            raise ShopeeApiError(
                code="bad_json", message="envelope không phải object", status=resp.status_code
            )
        error = str(payload.get("error") or "")
        if error:
            raise api_error(
                code=error,
                message=str(payload.get("message") or ""),
                status=resp.status_code,
                request_id=str(payload.get("request_id") or "") or None,
            )
        if resp.status_code >= 400:
            # Envelope sạch nhưng HTTP hỏng (cổng chặn trước khi vào API).
            raise ShopeeApiError(code="http_error", status=resp.status_code)
        response = payload.get("response")
        return response if isinstance(response, dict) else {}

    async def _get(self, path: str, extra: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._call("GET", path, query=extra)

    async def _handle_poll_error(self, what: str, exc: Exception, backoff: Backoff) -> None:
        kind = classify_error(exc)
        if kind == "auth" and isinstance(exc, ShopeeApiError):
            self.last_error = auth_error_message(exc)
            logger.error("%s — tạm dừng %.0fs rồi thử lại.", self.last_error, AUTH_BACKOFF_S)
            await asyncio.sleep(AUTH_BACKOFF_S)
            return
        if kind == "rate_limit" and isinstance(exc, ShopeeApiError):
            self.last_error = rate_limit_message(exc)
            logger.error("%s", self.last_error)
            await asyncio.sleep(RATE_LIMIT_BACKOFF_S)
            return
        delay = backoff.next_delay()
        detail = exc.code if isinstance(exc, ShopeeApiError) else type(exc).__name__
        self.last_error = f"{what}: {detail}"
        logger.warning("%s thất bại: %s; thử lại sau %.1fs", what, detail, delay)
        await asyncio.sleep(delay)

    async def _session_has_ended(self, session_id: str) -> bool:
        """True chỉ khi ``get_session_detail`` nói chắc ``status == 2``.

        Hỏi lỗi thì trả False: không biết chắc thì coi là "chưa phát" (chờ),
        chứ không kết thúc bộ thu của một buổi live có thể vẫn sắp lên sóng.
        """
        try:
            detail = await self._get(PATH_DETAIL, {"session_id": session_id})
        except ShopeeApiError:
            return False
        try:
            return int(str(detail.get("status"))) == STATUS_ENDED
        except ValueError:
            return False

    # -- comments ----------------------------------------------------------

    @staticmethod
    def _new_comments(
        items: Iterable[dict[str, Any]], seen: deque[str], seen_set: set[str]
    ) -> list[RawComment]:
        """Parse một trang, bỏ bình luận đã trả ở lần poll trước.

        Khử trùng lặp là **bắt buộc**, không phải tối ưu: cửa sổ 10 s và nhịp
        poll 5 s cố ý chồng lấn, nên mỗi bình luận được Shopee trả ~2 lần.
        """
        fresh: list[RawComment] = []
        for item in items:
            comment = parse_comment(item)
            if comment is None or comment.ext_id in seen_set:
                continue
            if len(seen) == seen.maxlen:
                seen_set.discard(seen[0])
            seen.append(comment.ext_id)
            seen_set.add(comment.ext_id)
            fresh.append(comment)
        return fresh

    async def get_latest_comment_page(self, session_id: str, offset: int = 0) -> dict[str, Any]:
        """Một trang thô của ``get_latest_comment_list`` (cửa sổ 10 s).

        Đây đúng là lời gọi :meth:`iter_comments` dùng; script kiểm tra gọi nó
        để thử đường dữ liệu mà không phải chạy vòng poll.
        """
        self.require_credentials()
        return await self._get(PATH_COMMENTS, {"session_id": session_id, "offset": offset})

    async def iter_comments(
        self, session_id: str, poll_s: float = DEFAULT_POLL_S
    ) -> AsyncIterator[RawComment]:
        """Yield bình luận bằng cách poll cửa sổ 10 giây của Shopee.

        Không có con trỏ ``since``: mỗi lần poll lấy lại cả cửa sổ và lọc trùng
        theo ``comment_id``. Vì vậy nhịp poll **phải** nhỏ hơn cửa sổ — quá
        :data:`MAX_SAFE_POLL_S` thì hàm này ném ``ValueError`` ngay lập tức chứ
        không chạy rồi mất dữ liệu âm thầm.

        Phiên không đang phát: nếu ``get_session_detail`` xác nhận đã kết thúc
        thì dừng êm (nguồn kết thúc); còn lại ném :class:`ShopeeNotLiveError`
        và **không tự chờ** — nơi gọi phải bắt lỗi đó rồi chờ lên sóng (xem
        hợp đồng ở lớp lỗi). Lỗi vùng / sai phiên ném ngay, không thử lại.
        """
        if poll_s > MAX_SAFE_POLL_S:
            raise ValueError(
                f"poll_s={poll_s:.1f}s vượt ngưỡng an toàn {MAX_SAFE_POLL_S:.0f}s: "
                f"get_latest_comment_list CHỈ trả bình luận trong "
                f"{COMMENT_WINDOW_S:.0f}s gần nhất, poll chậm hơn là MẤT bình luận "
                "vĩnh viễn (không có con trỏ để lấy lại). Giảm poll_s xuống."
            )
        self.require_credentials()
        seen: deque[str] = deque(maxlen=_SEEN_IDS_MAX)
        seen_set: set[str] = set()
        backoff = Backoff(base_s=poll_s, cap_s=max(poll_s, RETRY_CAP_S))
        while True:
            offset = 0
            batch: list[RawComment] = []
            loi_tam_thoi: ShopeeApiError | None = None
            loi_dung: ShopeeApiError | None = None
            da_ket_thuc = False
            for _page in range(MAX_PAGES_PER_POLL):
                try:
                    data = await self._get(
                        PATH_COMMENTS, {"session_id": session_id, "offset": offset}
                    )
                except ShopeeNotLiveError as exc:
                    if await self._session_has_ended(session_id):
                        logger.info("phiên Shopee Live đã kết thúc (status=2) — dừng thu bình luận")
                        da_ket_thuc = True
                    else:
                        self.last_error = str(exc)
                        loi_dung = exc
                    break
                except (ShopeeRegionError, ShopeeSessionError) as exc:
                    self.last_error = str(exc)
                    loi_dung = exc
                    break
                except ShopeeApiError as exc:
                    loi_tam_thoi = exc
                    break
                items = data.get("list") or []
                batch.extend(self._new_comments(items, seen, seen_set))
                nxt = next_offset(data)
                if not items or nxt is None or nxt == offset:
                    break
                offset = nxt
            else:
                logger.warning(
                    "poll bình luận: dừng ở %d trang trong một lần poll — phòng live "
                    "quá đông; dữ liệu vẫn đủ nhưng hãy ghi nhận vào nhật ký phiên.",
                    MAX_PAGES_PER_POLL,
                )
            if loi_tam_thoi is None and loi_dung is None:
                self.last_error = None
                backoff.reset()

            # Trả những gì ĐÃ đọc được kể cả khi một trang sau hỏng (kiểm toán
            # 17/09/2026). ``_new_comments`` đã đưa các id này vào seen-set, nên
            # bỏ batch ở đây là mất chúng vĩnh viễn: lần poll lại đọc đúng cửa
            # sổ 10 giây đó và coi mọi bình luận trên trang đầu là "đã thấy" —
            # cùng loại lỗi đã sửa cho Facebook.
            for comment in sorted(batch, key=lambda c: c.ts_utc):
                yield comment

            if da_ket_thuc:
                return
            if loi_dung is not None:
                raise loi_dung
            if loi_tam_thoi is not None:
                await self._handle_poll_error("poll bình luận", loi_tam_thoi, backoff)
                continue
            await asyncio.sleep(poll_s)

    # -- viewers -----------------------------------------------------------

    async def iter_viewers(
        self, session_id: str, every_s: float = DEFAULT_TICK_S
    ) -> AsyncIterator[RawTick]:
        """Yield số người xem đồng thời (``ccu``) mỗi ``every_s`` giây.

        Dừng khi ``get_session_detail`` báo ``status == 2`` (đã kết thúc).
        Trạng thái được hỏi TRƯỚC: tài liệu liệt kê lỗi "is not ongoing" cho
        ``get_session_metric``, nên hỏi metric trước thì không phân biệt được
        "chưa phát" với "đã kết thúc". Chưa phát ⇒ ném
        :class:`ShopeeNotLiveError`, không tự chờ (cùng hợp đồng với
        :meth:`iter_comments`).
        """
        self.require_credentials()
        backoff = Backoff(base_s=every_s, cap_s=max(every_s, RETRY_CAP_S))
        while True:
            try:
                detail = await self._get(PATH_DETAIL, {"session_id": session_id})
                status = detail.get("status")
                if status is not None and int(status) == STATUS_ENDED:
                    logger.info("phiên Shopee Live đã kết thúc (status=2) — dừng đếm người xem")
                    return
                metric = await self._get(PATH_METRIC, {"session_id": session_id})
            except (ShopeeRegionError, ShopeeSessionError, ShopeeNotLiveError):
                raise
            except ShopeeApiError as exc:
                await self._handle_poll_error("poll người xem", exc, backoff)
                continue
            self.last_error = None
            backoff.reset()
            ccu = metric.get("ccu")
            if ccu is not None:
                yield RawTick(
                    platform="shopee",
                    ts_utc=datetime.now(UTC),
                    viewers=float(ccu),
                )
            await asyncio.sleep(every_s)

    # -- conversion signals ------------------------------------------------

    async def get_session_metric(self, session_id: str) -> dict[str, Any]:
        """Chỉ số thời gian thực của phiên: ``gmv``, ``orders``, ``atc``,
        ``ctr``, ``ccu``, ``peak_ccu``, ``likes``, ``comments``, ``shares``,
        ``views``, ``avg_viewing_duration``.

        Đây là các số **cộng dồn từ đầu phiên**, không phải theo khối. Muốn số
        theo khối switchback thì lấy **hiệu** giữa hai mốc đầu/cuối khối — và
        phải ghi rõ trong phương pháp rằng biến kết quả là sai phân của một
        bộ đếm cộng dồn, chứ không phải sự kiện đơn lẻ có dấu thời gian.
        """
        self.require_credentials()
        return await self._get(PATH_METRIC, {"session_id": session_id})

    async def get_session_detail(self, session_id: str) -> dict[str, Any]:
        """Metadata phiên: ``title``, ``status``, ``start_time``, ``end_time``."""
        self.require_credentials()
        return await self._get(PATH_DETAIL, {"session_id": session_id})

    # -- actuator ----------------------------------------------------------

    async def update_show_item(self, session_id: str | int, item_id: str | int) -> dict[str, Any]:
        """Ghim sản phẩm đang giới thiệu qua API chính thức ``v2.livestream.update_show_item``.

        Theo tài liệu gốc: ``POST``, tham số chung (đã ký bằng ``user_id``) ở
        query, thân JSON ``{session_id, item_id, shop_id}`` — cả ba ``int64``,
        cả ba bắt buộc. Vì vậy ``SHOPEE_SHOP_ID`` chỉ bắt buộc ở đây.

        Cố ý **không tự thử lại**: một lệnh ghim đến muộn sẽ đặt sản phẩm lên
        màn hình ở SAI khối của lịch switchback. Lỗi nổi lên cho nơi gọi quyết
        định. Chưa nối vào route nào.
        """
        self.require_credentials(need_shop_id=True)
        body = {
            "session_id": _as_int("session_id", session_id),
            "item_id": _as_int("item_id", item_id),
            "shop_id": _as_int("SHOPEE_SHOP_ID", self._shop_id),
        }
        return await self._call("POST", PATH_SHOW_ITEM, body=body)

    async def aclose(self) -> None:
        if self._owns_client:
            await self._client.aclose()
